### ISSUE TITLE
more efficient setting of small magnitude elements

### ISSUE THREAD

**Issue by conradsnicta** [beanb2/intkrige#1]
The following code can be made more efficient by replacing the relatively costly non-contiguous submatrices with the simpler and faster [.clean()](http://arma.sourceforge.net/docs.html#clean) function. For example: `lam.clean(threshold)`
https://github.com/beanb2/intkrige/blob/05864a0a8ca171d21c10cc195a9e1389446c2b9c/src/nrShell.cpp#L277-L278

https://github.com/beanb2/intkrige/blob/05864a0a8ca171d21c10cc195a9e1389446c2b9c/src/nrShell.cpp#L338-L339

**Comment by beanb2** [comment]
Thank you for this recommendation. All instances of the above case have been replaced with the recommended .clean function and pushed to the repository.
